### ISSUE TITLE
member function `setOverriddenGrades()` is not defined

### ISSUE THREAD

**Issue by dpshelio** [Submitty/Submitty#10185]
**Describe the bug**

Found that the member function is not defined after trying to generate a grade summary. I've got the following traceback in the logs:
```
13:52:53 02/14/2024 - FATAL ERROR
Error (Code: 0) thrown in /usr/local/submitty/site/app/controllers/admin/ReportController.php (Line 245) by:
            $graded_gradeable->setOverriddenGrades($this->all_overrides[$user->getId()][$graded_gradeable->getGradeableId()] ?? null);


Message:
Call to a member function setOverriddenGrades() on null

Stack Trace:
#0 /usr/local/submitty/site/app/controllers/admin/ReportController.php(282): app\controllers\admin\ReportController->mergeGradedGradeables()
#1 /usr/local/submitty/site/app/controllers/admin/ReportController.php(291): app\controllers\admin\ReportController->app\controllers\admin\{closure}()
#2 /usr/local/submitty/site/app/controllers/admin/ReportController.php(97): app\controllers\admin\ReportController->generateReportInternal()
#3 unknown file(unknown line): app\controllers\admin\ReportController->generateGradeSummaries()
#4 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(262): call_user_func_array()
#5 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(240): app\libraries\routers\WebRouter->run()
#6 /usr/local/submitty/site/public/index.php(149): app\libraries\routers\WebRouter::getWebResponse()

URL: https://<url>/courses/<term>/<course>/reports/summaries
```

After going to the file, I looked where that `setOverriddenGrades()` gets defined and found it nowhere, only where it's used:

https://github.com/Submitty/Submitty/blob/350ffaee643f26fbaa4bb695b4bb0249602efc60/site/app/controllers/admin/ReportController.php#L246 

**Expected behavior**

I don't know what's the expected behaviour should be as in my case, my course should not have a need for merging grades.

**To Reproduce**
I don't really know because same course with similar setup doesn't produce this error. i.e., doesn't get into this block of code https://github.com/Submitty/Submitty/blob/350ffaee643f26fbaa4bb695b4bb0249602efc60/site/app/controllers/admin/ReportController.php#L289-L293

Why this happens to this particular course it's still a mystery for me and I'm asking on zulip about it.

1. 
2. 
3. 

**Configuration**
 - OS: Linux
 - Browser: Firefox, I've also tried with chromium.

**Screenshots**

**Additional context**

While exploring the server error I got I found this issue, but I know there may be something in this particular course that it's getting into that. But I don't know what it is. I'm adding that on a Zulip thread. I'll update here if that's related with the missing definition of this function, or as a new issue if it's unrelated.

**Comment by ProgrammingPirates** [comment]
Hell Sir @dpshelio i want to work on this issue, can you assign me please

**Comment by bmcutler** [comment]
Hi @ProgrammingPirates 

Thank you for your interest in the Submitty open source project.
We welcome contributions from new developers!
However we do not use the Github issue 'assign' feature for first time prospective contributors.

Please read our documentation on how to to get started with Submitty:
https://submitty.org/developer/getting_started/index
Specifically in setting up your development environment:
https://submitty.org/developer/getting_started/vm_install_using_vagrant
And making a pull request:
https://submitty.org/developer/getting_started/make_a_pull_request
You do not need to be assigned to an issue to create a pull request that will be reviewed by our team and then merged if it appropriately resolves the issue.
We also encourage you to join our Zulip server to discuss technical questions:
https://submitty.org/index/contact

**Comment by bmcutler** [comment]
Additional information:

This bug was probably caused by manual importing of student files & database content for a gradeable and perhaps the database has an incomplete or inconsistent information.  It may be hard to reproduce this bug without direct access to the specific system and custom use case.
