### ISSUE TITLE
Course materials site error  (frog robot)

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#10455]
**Describe the bug**

Here's a recent error stack trace in our /var/local/submitty/logs/site_errors/ directory

I do not have a report from the user or step-by-step instructions on how to reproduce.

```
14:20:55 05/21/2024 - FATAL ERROR
ValueError (Code: 0) thrown in /usr/local/submitty/site/app/libraries/FileUtils.php (Line 574) by:
            $type = mime_content_type($tmp_name);

Message:
mime_content_type(): Argument #1 ($filename) cannot be empty

Stack Trace:
#0 /usr/local/submitty/site/app/libraries/FileUtils.php(574): mime_content_type()
#1 /usr/local/submitty/site/app/libraries/FileUtils.php(645): app\libraries\FileUtils::app\libraries\{closure}()
#2 /usr/local/submitty/site/app/controllers/course/CourseMaterialsController.php(680): app\libraries\FileUtils::validateUploadedFiles()
#3 unknown file(unknown line): app\controllers\course\CourseMaterialsController->ajaxUploadCourseMaterialsFiles()
#4 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(262): call_user_func_array()
#5 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(240): app\libraries\routers\WebRouter->run()
#6 /usr/local/submitty/site/public/index.php(149): app\libraries\routers\WebRouter::getWebResponse()

URL: https://submitty.cs.rpi.edu//courses/u24/REDACTED/course_materials/upload
```

**Comment by bmcutler** [comment]
not sure how to reproduce
