### ISSUE TITLE
Docker UI generates errors in CI occasionally

### ISSUE THREAD

**Issue by williamjallen** [Submitty/Submitty#10553]
**Describe the bug**
I've observed the following error in our CI intermittently:

Text copied from [this](https://github.com/Submitty/Submitty/actions/runs/9493351310/job/26161899402?pr=10546) workflow run.

```
Site Errors Generated!

Contents:
00:00:49 06/13/2024 - FATAL ERROR
ValueError (Code: 0) thrown in /usr/local/submitty/site/app/views/admin/DockerView.php (Line 103) by:
            $content_2rpos = strrpos($content, "[Last ran", -35);


Message:
strrpos(): Argument #3 ($offset) must be contained in argument #1 ($haystack)

Stack Trace:
#0 /usr/local/submitty/site/app/views/admin/DockerView.php(103): strrpos()
#1 unknown file(unknown line): app\views\admin\DockerView->displayDockerPage()
#2 /usr/local/submitty/site/app/libraries/Output.php(248): call_user_func_array()
#3 /usr/local/submitty/site/app/libraries/Output.php(217): app\libraries\Output->renderTemplate()
#4 /usr/local/submitty/site/app/libraries/response/WebResponse.php(43): app\libraries\Output->renderOutput()
#5 /usr/local/submitty/site/app/libraries/response/MultiResponse.php(107): app\libraries\response\WebResponse->render()
#6 /usr/local/submitty/site/public/index.php(160): app\libraries\response\MultiResponse->render()

URL: http://localhost//admin/docker
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

**Expected behavior**
The CI should be reliable.

**Comment by powe97** [comment]
After some code digging and investigating CI runs, I've found that there are actually two different issues with the Docker UI test. Firstly, the one that this issue addresses. This site error
```
Site Errors Generated!

Contents:
00:00:49 06/13/2024 - FATAL ERROR
ValueError (Code: 0) thrown in /usr/local/submitty/site/app/views/admin/DockerView.php (Line 103) by:
            $content_2rpos = strrpos($content, "[Last ran", -35);
```
appears to be the result of a race condition. The logic in DockerView is roughly
```
if (there exists at least one file in var/local/submitty/logs/docker) then {
        $content = contents of most recent log file in that directory
        $content_2rpos = strrpos($content, "[Last ran", -35);
}
```
The `[Last ran` is always in the docker logfile, but if PHP sees the file before the Docker job is done writing to it, then that line doesn't exist and `strrpos` throws an error. I'm not sure how to address this issue, but it looks like a typical race condition to me.

**Comment by powe97** [comment]
The second issue is when docker_ui fails. This happens but it's rare and I don't have an example of it to show unfortunately. The Cypress test makes use of `cy.waitAndReloadUntil`,
https://github.com/Submitty/Submitty/blob/4ce524fe7903563d5992019483eccd107859c299/site/cypress/e2e/Cypress-UI/docker_ui.spec.js#L56-L62
which is hardcoded to wait a maximum of 10 seconds before failing. Naturally if for whatever reason the job takes longer than that then docker_ui will fail.

It appears to be designed this way because the docker update job does not "notify" the user when it’s done, so the Cypress test just ballparks that it’ll take 10 seconds max. We could set up a websocket that automatically reloads the page when the job is done and remove the static wait, and that would solve the problem, but this is a bit involved.

**Comment by williamjallen** [comment]
Would it be reasonable to just bump the timeout for `cy.waitAndReloadUntil()` to 30 seconds to resolve this?
