### ISSUE TITLE
frog robot on Autograding Status page.

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#10952]
**Describe the bug**

I'm not sure how to reproduce this, but we see this error in the logs :
This is for the "Autograding Status" page that is available to faculty users.
This page auto-updates, so instructors/admins can have the page open indefinitely, and this error pops up sometimes.

```
21:21:24 09/15/2024 - FATAL ERROR
TypeError (Code: 0) thrown in /usr/local/submitty/site/app/models/QueueItem.php (Line 45) by:
       $this->regrade = array_key_exists("regrade", $this->queue_obj);


Message:
array_key_exists(): Argument #2 ($array) must be of type array, bool given

Stack Trace:
#0 /usr/local/submitty/site/app/models/QueueItem.php(45): array_key_exists()
#1 /usr/local/submitty/site/app/libraries/GradingQueue.php(373): app\models\QueueItem->__construct()
#2 /usr/local/submitty/site/app/libraries/GradingQueue.php(332): app\libraries\GradingQueue->updateDetailedQueueCount()
#3 /usr/local/submitty/site/app/controllers/AutogradingStatusController.php(82): app\libraries\GradingQueue->getAutogradingInfo()
#4 /usr/local/submitty/site/app/controllers/AutogradingStatusController.php(44): app\controllers\AutogradingStatusController->getAutogradingInfo()
#5 unknown file(unknown line): app\controllers\AutogradingStatusController->getProgress()
#6 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(268): call_user_func_array()
#7 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(246): app\libraries\routers\WebRouter->run()
#8 /usr/local/submitty/site/public/index.php(149): app\libraries\routers\WebRouter::getWebResponse()

URL: https://submitty.cs.rpi.edu//autograding_status/get_update
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

**Comment by lavalleeale** [comment]
The issue is coming from line 44 of that file since `readJsonFile` can return false, indicating that the json file is either not created or in invalid json, I am looking into the root cause
