### ISSUE TITLE
duplicate key in late_day_cache

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#11131]
**Describe the bug**

I have reported this error in the past, but the developer working on late days @Youssef-Chip was unable to reproduce.

For some reason, instances of this error have spiked recently.  I don't have a report from any users about the problem (so I guess they must be just reloading the page and continuing or working around the problem.)

```
18:37:09 11/07/2024 - FATAL ERROR
app\exceptions\DatabaseException (Code: 0) thrown in /usr/local/submitty/site/app/libraries/database/AbstractDatabase.php (Line 166) by:
           throw new DatabaseException($dbalException->getMessage(), $query, $parameters);


Message:
An exception occurred while executing a query: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "ldc_g_user_id_unique"
DETAIL:  Key (g_id, user_id)=(GRADEABLEREDACTED, USERNAMEREDACTED) already exists.

Stack Trace:
#0 /usr/local/submitty/site/app/libraries/database/DatabaseQueries.php(2114): app\libraries\database\AbstractDatabase->query()
#1 /usr/local/submitty/site/app/libraries/database/DatabaseQueries.php(2042): app\libraries\database\DatabaseQueries->generateLateDayCacheForUser()
#2 /usr/local/submitty/site/app/libraries/database/DatabaseQueries.php(2069): app\libraries\database\DatabaseQueries->getLateDayCacheForUserGradeable()
#3 /usr/local/submitty/site/app/libraries/database/DatabaseQueries.php(2099): app\libraries\database\DatabaseQueries->getLateDayInfoForUserGradeable()
#4 /usr/local/submitty/site/app/views/grading/ElectronicGraderView.php(615): app\libraries\database\DatabaseQueries->getLateDayInfoForSubmitterGradeable()
#5 unknown file(unknown line): app\views\grading\ElectronicGraderView->detailsPage()
#6 /usr/local/submitty/site/app/libraries/Output.php(251): call_user_func_array()
#7 /usr/local/submitty/site/app/libraries/Output.php(220): app\libraries\Output->renderTemplate()
#8 /usr/local/submitty/site/app/controllers/grading/ElectronicGraderController.php(1073): app\libraries\Output->renderOutput()
#9 unknown file(unknown line): app\controllers\grading\ElectronicGraderController->showDetails()
#10 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(268): call_user_func_array()
#11 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(246): app\libraries\routers\WebRouter->run()
#12 /usr/local/submitty/site/public/index.php(149): app\libraries\routers\WebRouter::getWebResponse()
Extra Details:
	query: INSERT INTO late_day_cache
                   SELECT * FROM calculate_remaining_cache_for_user(?::text, ?)
	parameters:
		USERNAMEREDACTED
		5

URL: https://submitty.cs.rpi.edu//courses/f24/COURSEREDACTED/gradeable/ANOTHERGRADEABLEREDACTED/grading/details
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

**Comment by williamschen23** [comment]
```14:32:50 11/12/2024 - FATAL ERROR
app\exceptions\DatabaseException (Code: 0) thrown in /usr/local/submitty/site/app/libraries/database/AbstractDatabase.php (Line 166) by:
           throw new DatabaseException($dbalException->getMessage(), $query, $parameters);
Message:
An exception occurred while executing a query: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "ldc_g_user_id_unique"
DETAIL:  Key (g_id, user_id)=(REDACTEDGRADEAVLE, REDACTEDUSED) already exists.
Stack Trace:
#0 /usr/local/submitty/site/app/libraries/database/DatabaseQueries.php(1939): app\libraries\database\AbstractDatabase->query()
#1 /usr/local/submitty/site/app/controllers/grading/ElectronicGraderController.php(1791): app\libraries\database\DatabaseQueries->generateLateDayCacheForUsers()
#2 unknown file(unknown line): app\controllers\grading\ElectronicGraderController->showGrading()
#3 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(268): call_user_func_array()
#4 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(246): app\libraries\routers\WebRouter->run()
#5 /usr/local/submitty/site/public/index.php(149): app\libraries\routers\WebRouter::getWebResponse()
Extra Details:
query: INSERT INTO late_day_cache
                   (SELECT (cache_row).*
                        FROM
                       (SELECT
                           public.calculate_remaining_cache_for_user(user_id::text, ?) as cache_row
                       FROM users
                       ) calculated_cache
                   )
parameters:
5
URL: https://submitty.cs.rpi.edu//courses/f24/REDACTEDCOURSE/gradeable/ANOTHERREDACTEDGRADEABLE/grading/grade?sort=id&direction=ASC&from=ANONID&to=next&filter=default
```

**Comment by williamschen23** [comment]
Steps to reproduce:
1. Find a gradeable that is past due
2. Have two users click the preview grading button
3. See that one of them will have an error


Used a python script to simulate clicking things at the same time, 
```py
import pyautogui

pyautogui.click((170, 900)) # chrome
pyautogui.click((1160, 560)) # focus tab
pyautogui.click((1160, 560)) # click 
pyautogui.click((450, 500)) # focus other tab
pyautogui.click((450, 500)) # click
```
