### ISSUE TITLE
Publishing New Thread on Forum Throws Database Exception

### ISSUE THREAD

**Issue by KevinMackenzie** [Submitty/Submitty#2131]
```Oh no! Something irrecoverable has happened...

app\exceptions\DatabaseException (Code: 0) thrown in /usr/local/submitty/site/app/libraries/database/AbstractDatabase.php (Line 175) by:
            throw new DatabaseException($pdoException->getMessage(), $query, $parameters);


Message:
SQLSTATE[42703]: Undefined column: 7 ERROR:  column "merged_thread_id" of relation "threads" does not exist
LINE 1: ...INTO threads (title, created_by, pinned, deleted, merged_thr...
                                                             ^

Strack Trace:
#0 /usr/local/submitty/site/app/libraries/database/DatabaseQueries.php(188): app\libraries\database\AbstractDatabase->query('INSERT INTO threads (title, created_by, pinned, deleted, merged_thread_id, merged_post_id, is_visible) VALUES (?, ?, ?, ?, ?, ?, ?)', Array)
#1 /usr/local/submitty/site/app/controllers/forum/ForumController.php(163): app\libraries\database\DatabaseQueries->createThread('student', 'Test Thread', 'asdfasdfadsfasdfadsfadsfadsfdsadffeasdf', 0, 0, 0, 3)
#2 /usr/local/submitty/site/app/controllers/forum/ForumController.php(34): app\controllers\forum\ForumController->publishThread()
#3 /usr/local/submitty/site/public/index.php(262): app\controllers\forum\ForumController->run()
Extra Details:
query: INSERT INTO threads (title, created_by, pinned, deleted, merged_thread_id, merged_post_id, is_visible) VALUES (?, ?, ?, ?, ?, ?, ?)
parameters:
Test Thread
student
0
0
-1
-1
1
```
I was creating a new thread on the forum as "student" and got this error when submitting the thread.
![image](https://user-images.githubusercontent.com/3719964/41181559-2b162a40-6b40-11e8-9afc-a5ebda70c6cd.png)

**Comment by andrewaikens87** [comment]
@KevinMackenzie There have been some database changes, you should be able to run `update_database.py` to correct this. I believe the migration tool will be used for changes in the future. You can verify the changes have been made in the database.
