### ISSUE TITLE
Have autograder throw appropriate error if untrusted_execute errors

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#3372]
If the untrusted_execute script fails for whatever reason, the autograder will happily continue on assuming that it had worked, which then causes it to error out later with a cascade of unrelated errors that don't make a ton of sense:
```
2019-03-11 01:26:24.359 +0000 | UNKNOWN |       |             |                                                                             |                      |
Traceback (most recent call last):
  File "/usr/local/submitty/sbin/submitty_autograding_worker.py", line 176, in read_autograding_worker_json
    with open(ALL_WORKERS_JSON, 'r') as infile:
FileNotFoundError: [Errno 2] No such file or directory: '/var/local/submitty/autograding_TODO/autograding_worker.json'

2019-03-11 01:30:30.023 +0000 | UNKNOWN |       |             |                                                                             |                      |
Traceback (most recent call last):
  File "/usr/local/submitty/sbin/submitty_autograding_worker.py", line 176, in read_autograding_worker_json
    with open(ALL_WORKERS_JSON, 'r') as infile:
FileNotFoundError: [Errno 2] No such file or directory: '/var/local/submitty/autograding_TODO/autograding_worker.json'

2019-03-11 01:32:52.629 +0000 | tVD4OX |       | untrusted00 | s19/sample/submissions/grades_released_homework_autohiddenEC/student/1      |                      |
Traceback (most recent call last):
  File "/usr/local/submitty/sbin/autograder/grade_item.py", line 611, in grade_from_zip
    with open(os.path.join(tmp_work,"grade.txt")) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/local/submitty/autograding_tmp/untrusted00/tmp/TMP_WORK/grade.txt'

2019-03-11 01:32:52.637 +0000 | tVD4OX |       | untrusted00 | s19/sample/submissions/grades_released_homework_autohiddenEC/student/1      |                      |
Traceback (most recent call last):
  File "/usr/local/submitty/sbin/autograder/grade_item.py", line 664, in grade_from_zip
    shutil.copy(os.path.join(tmp_work,"grade.txt"),tmp_results)
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/var/local/submitty/autograding_tmp/untrusted00/tmp/TMP_WORK/grade.txt'

2019-03-11 01:32:52.638 +0000 | tVD4OX |       | untrusted00 | s19/sample/submissions/grades_released_homework_autohiddenEC/student/1      |                      |
Traceback (most recent call last):
  File "/usr/local/submitty/sbin/autograder/grade_item.py", line 700, in grade_from_zip
    with open(os.path.join(tmp_work,"results.json"), 'r') as read_file:
FileNotFoundError: [Errno 2] No such file or directory: '/var/local/submitty/autograding_tmp/untrusted00/tmp/TMP_WORK/results.json'

2019-03-11 01:32:53.356 +0000 | ~SHIP~ |       |             |                                                                             |                      |
Traceback (most recent call last):
  File "/usr/local/submitty/sbin/submitty_autograding_shipper.py", line 315, in unpack_job
    success = packer_unpacker.unpack_grading_results_zip(which_machine,which_untrusted,local_results_zip)
  File "/usr/local/submitty/sbin/autograder/packer_unpacker.py", line 318, in unpack_grading_results_zip
    str(queue_obj["version"]))
  File "/usr/local/submitty/sbin/autograder/insert_database_version_data.py", line 63, in insert_to_database
    non_hidden_non_ec += results['testcases'][i]['points']
IndexError: list index out of range
```

We should modify the autograder such that if untrusted_execute fails, the autograder fails there.

**Comment by rohithbalaji123** [comment]
@MasterOdin and @bmcutler . I would like to work on this issue!
Can you help me reproduce this bug?

**Comment by MasterOdin** [comment]
You can force a failure in untrusted_execute by modifying https://github.com/Submitty/Submitty/blob/master/.setup/untrusted_execute.c and just putting `exit(1)` at the start of the main function. Ideally, we'd then see some meaningful error message in https://submitty.org/instructor/log_files#autograding-queue-logs or someway to tell that untrusted_execute was the reason for the failure. Working through the entirety of the issue will require if gating around the exit for specific conditions to test the various points untrusted execute is called.
