### ISSUE TITLE
Possible resurfacing of 3513

### ISSUE THREAD

**Issue by linhbngo** [Submitty/Submitty#4470]
This seems to be a resurfacing of [issue 3513](https://github.com/Submitty/Submitty/issues/3153). An instructor creates a new course, but not able to create and submit assignments for gradeables. 

I checked and found the submitted file, but the autograding process did not run, and we have the following errors in log:

```
                                           |                      | ERROR: the submission directory does not exist /var/local/submitty/courses/fall2019/csc141_01/submissions/assignment_0/lcui/3
2019-09-13 10:07:50.600 -0400 | ~SHIP~ |       |             |                                                                             |                      | ERROR: failed preparing submission zip or accessing next to grade ('ERROR: the submission directory does not exist', '/var/local/submitty/courses/fall2019/csc141_01/submissions/assignment_0/lcui/3')
2019-09-13 10:07:50.600 -0400 | ~SHIP~ |       |             |                                                                             |                      | primary ERROR unable to prepare job: /var/local/submitty/to_be_graded_queue/fall2019__csc141_01__assignment_0__lcui__3
2019-09-13 10:52:36.548 -0400 | hmg1AP |       |             |       
```

The current Submitty installation is from ref ce0074a87d98e358ec2151843e9435d292f86ce4

**Comment by MasterOdin** [comment]
For our reference, how much of this directory tree (`/var/local/submitty/courses/fall2019/csc141_01/submissions/assignment_0/lcui/3`) does exist?

And I'm guessing there were no PHP errors shown or anything when submitting the assignment via the Web GUI?

**Comment by emaicus** [comment]
Hi @linhbngo, could you also provide us with the contents of the following files: 
```
/var/local/submitty/logs/autograding/stack_traces/stack_traces_20190913.txt
/usr/local/submitty/config/version.json
```

**Comment by linhbngo** [comment]
@MasterOdin 
- The submissions for that directory tree exists in directories part1 and part2. I crossed check the contents with another submission from a course that worked (created earlier in the summer), and the content structure matches. 
- There is no PHP error shown on the Web GUI, except for a line saying that the submission cannot be graded, please contact instructor. 

@emaicus 
- Content of stack_traces_20190913.txt:

more /var/local/submitty/logs/autograding/stack_traces/stack_traces_20190913.txt
2019-09-13 10:06:09.284 -0400 | ~SHIP~ |       |             |
                                                                   |
                  |
Traceback (most recent call last):
  File "/usr/local/submitty/sbin/submitty_autograding_shipper.py", line
176, in prepare_job
    autograding_zip_tmp,submission_zip_tmp = packer_unpacker.prepare_aut
ograding_and_submission_zip(which_machine,which_untrusted,next_directory
,next_to_grade)
  File "/usr/local/submitty/sbin/autograder/packer_unpacker.py", line 13
2, in prepare_autograding_and_submission_zip
    raise RuntimeError("ERROR: the submission directory does not exist",
 submission_path)
RuntimeError: ('ERROR: the submission directory does not exist', '/var/l
ocal/submitty/courses/fall2019/csc141_01/submissions/assignment_0/lcui/1
')

2019-09-13 10:07:10.882 -0400 | ~SHIP~ |       |             |
                                                                   |
                  |
Traceback (most recent call last):
  File "/usr/local/submitty/sbin/submitty_autograding_shipper.py", line
176, in prepare_job
    autograding_zip_tmp,submission_zip_tmp = packer_unpacker.prepare_aut
ograding_and_submission_zip(which_machine,which_untrusted,next_directory
,next_to_grade)
  File "/usr/local/submitty/sbin/autograder/packer_unpacker.py", line 13
2, in prepare_autograding_and_submission_zip
    raise RuntimeError("ERROR: the submission directory does not exist",
 submission_path)
RuntimeError: ('ERROR: the submission directory does not exist', '/var/l
ocal/submitty/courses/fall2019/csc141_01/submissions/assignment_0/lcui/2
')

2019-09-13 10:07:50.599 -0400 | ~SHIP~ |       |             |
                                                                   |
                  |
Traceback (most recent call last):
  File "/usr/local/submitty/sbin/submitty_autograding_shipper.py", line
176, in prepare_job
    autograding_zip_tmp,submission_zip_tmp = packer_unpacker.prepare_aut
ograding_and_submission_zip(which_machine,which_untrusted,next_directory
,next_to_grade)
  File "/usr/local/submitty/sbin/autograder/packer_unpacker.py", line 13
2, in prepare_autograding_and_submission_zip
    raise RuntimeError("ERROR: the submission directory does not exist",
 submission_path)
RuntimeError: ('ERROR: the submission directory does not exist', '/var/l
ocal/submitty/courses/fall2019/csc141_01/submissions/assignment_0/lcui/3
')

2019-09-13 10:52:36.548 -0400 | ~SHIP~ |       |             |
                                                                   |
                  |
Traceback (most recent call last):
  File "/usr/local/submitty/sbin/submitty_autograding_shipper.py", line
176, in prepare_job
    autograding_zip_tmp,submission_zip_tmp = packer_unpacker.prepare_aut
ograding_and_submission_zip(which_machine,which_untrusted,next_directory
,next_to_grade)
  File "/usr/local/submitty/sbin/autograder/packer_unpacker.py", line 13
2, in prepare_autograding_and_submission_zip
    raise RuntimeError("ERROR: the submission directory does not exist",
 submission_path)
RuntimeError: ('ERROR: the submission directory does not exist', '/var/l
ocal/submitty/courses/fall2019/csc141_05/submissions/assignment_0/lcui/1
')


- Content of version.json

more /usr/local/submitty/config/version.json
{
  "installed_commit": "ce0074a87d98e358ec2151843e9435d292f86ce4",
  "short_installed_commit": "ce0074a8",
  "most_recent_git_tag": "v.18.06.00"
}

**Comment by emaicus** [comment]
Hello @linhbngo,

Your ```version.json``` is indicating that you are on a previous release, and notably one prior to a recent stability rewrite of the related ```autograder/autograder``` module. If at all possible, please pull in the most recent master and update, as it is very possible that it contains a fix for the issue you are experiencing. If the problem persists, please post back here with the new output of your ```stack_traces.txt```.

**Comment by linhbngo** [comment]
I have updated Submitty and the error went away. Another error related to adding new student/instructor also went away. 

Thanks!

**Comment by emaicus** [comment]
Glad to hear it @linhbngo!
