### ISSUE TITLE
E2E test occasionally fails due to ElementClickInterceptedException

### ISSUE THREAD

**Issue by zjxiaohan** [Submitty/Submitty#4810]
**Describe the bug**
```
======================================================================
ERROR: test_forum_merge_thread (e2e.test_forum.TestForum)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Submitty/Submitty/tests/e2e/test_forum.py", line 260, in test_forum_merge_thread
    self.find_posts(reply2, must_exists=True, check_attachment=reply2_attachment)
  File "/home/travis/build/Submitty/Submitty/tests/e2e/test_forum.py", line 129, in find_posts
    posts[0].find_element(By.XPATH, ".//a[starts-with(@id, 'button_attachments_')]").click()
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a href="#" id="button_attachments_46" onclick="loadInlineImages('[[&quot;http:\/\/localhost\/f19\/sample\/display_file?dir=forum_attachments&amp;path=%2Fvar%2Flocal%2Fsubmitty%2Fcourses%2Ff19%2Fsample%2Fforum_attachments%2F13%2F46%2Ftmpu22e6f_s.png&quot;,&quot;46_0&quot;,&quot;tmpu22e6f_s.png&quot;],&quot;attachments_46&quot;]');" class="attachment-btn btn btn-default btn-sm" type="button">...</a> is not clickable at point (841, 785). Other element would receive the click: <div class="post_box viewed_post important" id="45" style="margin-left:0px;" reply-level="1">...</div>
```

**To Reproduce**
See:
https://travis-ci.com/Submitty/Submitty/jobs/257938351
https://travis-ci.com/Submitty/Submitty/jobs/258963653
https://travis-ci.com/Submitty/Submitty/jobs/259131779

**Comment by ektedar** [comment]
Could you go a little more into depth on the problem and what you are trying to do?

Couple of assumptions that I will go off from is that you are probably automating the tests between two pages (or pop-up modals).  The discrepancy is happening on the transition of the pages with Selenium's execution speed, which is faster therefore the button element is intercepted.  The poor man's way would be to add a small sleep timer right before the failure line.

For my case, I had a scenario where I clicked "Save" on a modal and the animation of the modal exiting and going back to the index page was slower than Selenium's execution speed and caused the inconsistent interception issue.
