### ISSUE TITLE
Flakiness in accessibility testing

### ISSUE THREAD

**Issue by MasterOdin** [Submitty/Submitty#5483]
Testing against master, I noticed that the E2E suite would fail occasionally with the following error:
```
======================================================================
ERROR: test_w3_validator (e2e.test_accessibility.TestAccessibility) (url='/s20/sample/course_materials')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Submitty/Submitty/tests/e2e/test_accessibility.py", line 95, in validatePages
    for error in response.json()['messages']:
  File "/opt/pyenv/versions/3.8.1/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/pyenv/versions/3.8.1/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/pyenv/versions/3.8.1/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/pyenv/versions/3.8.1/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
======================================================================
ERROR: test_w3_validator (e2e.test_accessibility.TestAccessibility) (url='/s20/sample/plagiarism')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Submitty/Submitty/tests/e2e/test_accessibility.py", line 108, in validatePages
    "html extract": error['extract'].strip(),
KeyError: 'extract'
```

Re-running the test would sometimes lead to the test passing. Not sure if it's an issue that the page just takes a bit too long to load or what.

**Comment by MasterOdin** [comment]
Different pages, same failures in https://travis-ci.com/github/Submitty/Submitty/jobs/345560463:

```
======================================================================
ERROR: test_w3_validator (e2e.test_accessibility.TestAccessibility) (url='/s20/sample/notifications')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Submitty/Submitty/tests/e2e/test_accessibility.py", line 108, in validatePages
    "html extract": error['extract'].strip(),
KeyError: 'extract'
======================================================================
ERROR: test_w3_validator (e2e.test_accessibility.TestAccessibility) (url='/s20/sample/graders')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Submitty/Submitty/tests/e2e/test_accessibility.py", line 108, in validatePages
    "html extract": error['extract'].strip(),
KeyError: 'extract'
```
