### ISSUE TITLE
Handle broken gradeables more gracefully

### ISSUE THREAD

**Issue by emaicus** [Submitty/Submitty#5710]
If gradeable creation fails, it currently makes it impossible to access the gradeables index (first page within a course). Ideally, we would handle this more gracefully. 

Here is an example of such an error:
```
Server Error
Oh no! Something irrecoverable has happened...

app\exceptions\DatabaseException (Code: 0) thrown in /usr/local/submitty/site/app/libraries/database/DatabaseQueries.php (Line 4183) by:
                throw new DatabaseException("Electronic gradeable didn't have an entry in the electronic_gradeable table!");


Message:
Electronic gradeable didn't have an entry in the electronic_gradeable table!

Stack Trace:
#0 unknown file(unknown line): app\libraries\database\DatabaseQueries->app\libraries\database\{closure}(Array)
#1 /usr/local/submitty/site/app/libraries/database/DatabaseRowIterator.php(56): call_user_func(Closure, Array)
#2 /usr/local/submitty/site/app/models/gradeable/GradeableList.php(72): app\libraries\database\DatabaseRowIterator->next()
#3 /usr/local/submitty/site/app/controllers/NavigationController.php(29): app\models\gradeable\GradeableList->__construct(app\libraries\Core)
#4 unknown file(unknown line): app\controllers\NavigationController->navigationPage()
#5 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(217): call_user_func_array(Array, Array)
#6 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(195): app\libraries\routers\WebRouter->run()
#7 /usr/local/submitty/site/public/index.php(127): app\libraries\routers\WebRouter::getWebResponse(Symfony\Component\HttpFoundation\Request, app\libraries\Core)
                  ,--.    ,--.
                 (( O))--(( O))
               ,'_`--'____`--'_`.
              _:  ____________  :_      _____
             | | ||::::::::::|| | |        \ \
             | | ||::::::::::|| | |         \
             | | ||::::::::::|| | |
             |_| |/__________\| |_|
               |________________|
            __..-'            `-..__
         .-| : .----------------. : |-.
       ,\ || | |\______________/| | || /.
      /`.\:| | ||  __  __  __  || | |;/,'\
     :`-._\;.| || '--''--''--' || |,:/_.-':
     |    :  | || .----------. || |  :    |
     |    |  | || '----SSt---' || |  |    |
     |    |  | ||   _   _   _  || |  |    |
     :,--.;  | ||  (_) (_) (_) || |  :,--.;
     (`-'|)  | ||______________|| |  (|`-')
      `--'   | |/______________\| |   `--'
             |____________________|
              `.________________,'
               (_______)(_______)
               (_______)(_______)
               (_______)(_______)
               (_______)(_______)
              |        ||        |
              '--------''--------'
```

**Comment by MasterOdin** [comment]
I strongly advocate for working on preventing these broken gradeables from entering the system at all, not make loading broken gradeables more graceful.

**Comment by emaicus** [comment]
Agreed 100%. This should absolutely _not_ make reviewing more lax. But in the unfortunate scenario that a broken gradeable does sneak it's way in, let's print a message rather than letting the whole site be taken down.

**Comment by emaicus** [comment]
Updated the issue to include adding an error message/banner.

**Comment by Kevin-MM** [comment]
As discussed in meetings, to make the gradeable creation process more robust we should implement database transactions while creating a new gradeable.
