### ISSUE TITLE
Visual Studio Code Extension

### ISSUE THREAD

**Issue by prestoncarman** [Submitty/Submitty#6245]
**What problem are you trying to solve with Submitty**
Integrate grading UI into the IDE which students are writing their code. For new students, it would be nice to cut down on the many places they have to go to complete an assignment.

**Describe the way you'd like to solve this problem**
Build an extension for Visual Studio Code that enables a student to:
* Trigger auto-grading on their assignment
* See auto-grading results
The process would be tightly integrated into the IDE, similar to the run button for executing their code.

**Thing to consider**
* These features could be added with a capable API from Submitty

**Additional context**
The goal would be to get students used to using the IDE without having to navigate to a web browser to see their test results. Update the Submitty grading process to look more closely with how typical unit testing works.

**Comment by shailpatels** [comment]
@prestoncarman Do you have an initial design in mind for what you want the API endpoint to look like? 

It sounds like from your use case you allow students to submit as many times as they want so the submission endpoint probably won't have any way to notify students of late submissions/late day usage/ etc. This could probably be built into its own endpoint if needed though.

**Comment by nilesh05apr** [comment]
Hello @shailpatels @prestoncarman is this task completed? if not I would like to work on this task, please share further details.

**Comment by shailpatels** [comment]
> Hello @shailpatels @prestoncarman is this task completed? if not I would like to work on this task, please share further details. 

This task is still open, we've done a lot of work related to the API but nothing touching auto grading. This is probably still a large task but probably the first place is to look at the existing API functionality

**Comment by ryanting01** [comment]
Hello! 
I am currently creating a Visual Studio Code extension and I am expanding the API functionality. I am trying to create an endpoint for students to submit a submission to a gradeable. I am trying to use this function https://github.com/Submitty/Submitty/blob/ed4fbf3f6485927f32ca8b1397af34d67084a304/site/app/controllers/student/SubmissionController.php#L1018 in an api endpoint like this:
`   
 /**
     * Submit a submission to a gradeable
     * @Route("/api/submit", methods={"POST"})
     *
     * @param string|null $user_id
     * @return MultiResponse
     */
    public function submitSubmission($user_id = null) {

        $this->addUploadFile("test1.txt", "", 1);

        $controller = new SubmissionController($this->core);
        $return = $controller->ajaxUploadSubmission('c_failure_messages');

    }
`
All dependancies should be working and it seems that I am getting an error whose origin doesn't seem to be related:

Oh no! Something irrecoverable has happened...

Error (Code: 0) thrown in /usr/local/submitty/site/app/libraries/database/DatabaseQueries.php (Line 5211) by:
        return $this->course_db->queryIterator(


Message:
Call to a member function queryIterator() on null

Stack Trace:
#0 /usr/local/submitty/site/app/libraries/database/DatabaseQueries.php(4961): app\libraries\database\DatabaseQueries->getGradeableConfigs()
#1 /usr/local/submitty/site/app/controllers/student/SubmissionController.php(49): app\libraries\database\DatabaseQueries->getGradeableConfig()
#2 /usr/local/submitty/site/app/controllers/student/SubmissionController.php(1040): app\controllers\student\SubmissionController->tryGetElectronicGradeable()
#3 /usr/local/submitty/site/app/controllers/HomePageController.php(78): app\controllers\student\SubmissionController->ajaxUploadSubmission()
#4 unknown file(unknown line): app\controllers\HomePageController->submitSubmission()
#5 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(262): call_user_func_array()
#6 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(170): app\libraries\routers\WebRouter->run()
#7 /usr/local/submitty/site/public/index.php(128): app\libraries\routers\WebRouter::getApiResponse()


Could anyone help with this problem? It seems that I should use Ajax to call the ajaxUploadSubmission function but I cannot seem to find any examples. I am not sure if this is the correct direction to go in at all or is it totally something else. 

Thanks in advance! 

Additional query:
Is there an extension being worked on right now? Or has this been put on pause for the moment, thanks!

**Comment by Pallavrai** [comment]
Hey, is this issue resolved ? if not then, can anyone provide me the function or specific directory which deals with the API and its permissions ?
