### ISSUE TITLE
Error on bulk submission

### ISSUE THREAD

**Issue by wusatosi** [Submitty/Submitty#7376]
**Describe the bug**
When I tried to upload a 46 pages pdf, 
the Robot error page reports the following error: (retrieved from log)
```
02:01:24 11/22/2021 - FATAL ERROR
app\exceptions\OutputException (Code: 0) thrown in /usr/local/submitty/site/app/libraries/Output.php (Line 360) by:
            throw new OutputException("{$e->getMessage()} in {$e->getFile()}:{$e->getLine()}");


Message:
Key "url" does not exist as the array is empty. in /usr/local/submitty/site/app/templates/submission/homework/BulkUploadBox.twig:39

Stack Trace:
#0 /usr/local/submitty/site/app/views/submission/HomeworkView.php(681): app\libraries\Output->renderTwigTemplate()
#1 /usr/local/submitty/site/app/views/submission/HomeworkView.php(73): app\views\submission\HomeworkView->renderBulkUploadBox()
#2 unknown file(unknown line): app\views\submission\HomeworkView->showGradeable()
#3 /usr/local/submitty/site/app/libraries/Output.php(222): call_user_func_array()
#4 /usr/local/submitty/site/app/libraries/Output.php(191): app\libraries\Output->renderTemplate()
#5 /usr/local/submitty/site/app/controllers/student/SubmissionController.php(195): app\libraries\Output->renderOutput()
#6 unknown file(unknown line): app\controllers\student\SubmissionController->showHomeworkPage()
#7 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(241): call_user_func_array()
#8 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(219): app\libraries\routers\WebRouter->run()
#9 /usr/local/submitty/site/public/index.php(131): app\libraries\routers\WebRouter::getWebResponse()

URL: http://localhost:1511//courses/f21/development/gradeable/c_failure_messages
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```
Refresh works, and the files are being properly splitted. 

**Expected behavior**
No error occurring. 

**To Reproduce**
I have not found a way to reproduce the error. 

**Configuration**
 - OS: Windows host, vagrant on ubuntu 20.04
 - Browser: Chrome

**Comment by wusatosi** [comment]
The referred code: https://github.com/Submitty/Submitty/blob/a7b11ba2c6aed94728eef7317bac067ec55c0f48/site/app/templates/submission/homework/BulkUploadBox.twig#L39

**Comment by shailpatels** [comment]
This issue is most likely the same as the comment in this issue https://github.com/Submitty/Submitty/issues/7191

When the python process is not finished moving the bulk upload split items and .pngs to place but the JSON file has been written to it can cause an issue where the PHP code tries to read resources that haven't been written yet.

This PR adds some error checking to that code section but yeah there is a need for more checks in other areas
https://github.com/Submitty/Submitty/pull/7344
