### ISSUE TITLE
Discussion Forum -- error in /var/local/submitty/logs/site_errors

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#7955]
This error was found in the site_errors log.
I don't have a report from a user about a problem, so I can't say how exactly it was produced.

-----------------------

00:09:15 05/24/2022 - FATAL ERROR
app\exceptions\DatabaseException (Code: 0) thrown in /usr/local/submitty/site/app/libraries/database/AbstractDatabase.php (Line 188) by:
            throw new DatabaseException($pdoException->getMessage(), $query, $parameters);

Message:
SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type integer: ""

Stack Trace:
#0 /usr/local/submitty/site/app/libraries/database/DatabaseQueries.php(794): app\libraries\database\AbstractDatabase->query()
#1 /usr/local/submitty/site/app/views/forum/ForumThreadView.php(713): app\libraries\database\DatabaseQueries->getFirstPostForThread()
#2 /usr/local/submitty/site/app/views/forum/ForumThreadView.php(607): app\views\forum\ForumThreadView->displayThreadList()
#3 unknown file(unknown line): app\views\forum\ForumThreadView->showAlteredDisplayList()
#4 /usr/local/submitty/site/app/libraries/Output.php(228): call_user_func_array()
#5 /usr/local/submitty/site/app/controllers/forum/ForumController.php(927): app\libraries\Output->renderTemplate()
#6 unknown file(unknown line): app\controllers\forum\ForumController->getSingleThread()
#7 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(241): call_user_func_array()
#8 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(219): app\libraries\routers\WebRouter->run()
#9 /usr/local/submitty/site/public/index.php(131): app\libraries\routers\WebRouter::getWebResponse()
Extra Details:
	query: SELECT * FROM posts WHERE parent_id = -1 AND thread_id = ?
	parameters:
		

URL: https://submitty.cs.rpi.edu//courses/u22/csci2600/forum/threads/single

**Comment by bmcutler** [comment]
@MBon1 Please ask @cjreed121 If you need tips on investigating or guessing the cause of this error and how to prevent it in the future.
