### ISSUE TITLE
Course Materials -- error in /var/local/submitty/logs/site_errors

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#7956]
This error was found in the site_errors log.
I don't have a report from a user about a problem, so I can't say how exactly it was produced.

---

10:31:36 05/24/2022 - FATAL ERROR
Doctrine\DBAL\Exception\DriverException (Code: 0) thrown in /usr/local/submitty/site/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php (Line 102) by:
        return new DriverException($message, $exception);

Message:
An exception occurred while executing 'SELECT t0.id AS id_1, t0.path AS path_2, t0.type AS type_3, t0.release_date AS release_date_4, t0.hidden_from_students AS hidden_from_students_5, t0.priorit
y AS priority_6, t0.url AS url_7, t0.url_title AS url_title_8 FROM course_materials t0 WHERE t0.id = ? LIMIT 1' with params ["\/var\/local\/submitty\/courses\/u22\/csci4460\/uploads\/course_mater
ials\/hidden"]:

SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type integer: "/var/local/submitty/courses/u22/csci4460/uploads/course_materials/hidden"

Stack Trace:
#0 /usr/local/submitty/site/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(182): Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException()
#1 /usr/local/submitty/site/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(159): Doctrine\DBAL\DBALException::wrapException()
#2 /usr/local/submitty/site/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(2226): Doctrine\DBAL\DBALException::driverExceptionDuringQuery()
#3 /usr/local/submitty/site/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1313): Doctrine\DBAL\Connection->handleExceptionDuringQuery()
#4 /usr/local/submitty/site/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(749): Doctrine\DBAL\Connection->executeQuery()
#5 /usr/local/submitty/site/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(243): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load()
#6 /usr/local/submitty/site/app/controllers/course/CourseMaterialsController.php(324): Doctrine\ORM\EntityRepository->findOneBy()
#7 unknown file(unknown line): app\controllers\course\CourseMaterialsController->ajaxEditCourseMaterialsFiles()
#8 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(241): call_user_func_array()
#9 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(219): app\libraries\routers\WebRouter->run()
#10 /usr/local/submitty/site/public/index.php(131): app\libraries\routers\WebRouter::getWebResponse()

URL: https://submitty.cs.rpi.edu//courses/u22/csci4460/course_materials/edit

**Comment by bmcutler** [comment]
@MBon1 Please ask @cjreed121 If you need tips on investigating or guessing the cause of this error and how to prevent it in the future.
