### ISSUE TITLE
advancing ta grading from cancelled submission to next student gets frog robot

### ISSUE THREAD

**Issue by bmcutler** [Submitty/Submitty#8533]
**Describe the bug**
When grading a scanned exam by rotating section.
Grading is almost complete.  There are just a few ungraded students in the NULL rotating section.  These aren't students in the course, but members of the teaching staff with practice upload submissions.

I click into one of the ungraded staff submissions.  I mark that submission as 'cancelled'.  Then I click next to advance to the next user with a submission (so I can cancel that too), also in the NULL rotating section.  And I get the frog robot.  It seems to matter both that the current user is cancelled and that the next user in the section is ungraded.  Not all situations cause the error, but I was able to reproduce it as described above.

Here's the error log:

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
11:33:55 10/22/2022 - FATAL ERROR
TypeError (Code: 0) thrown in /usr/local/submitty/site/app/controllers/AbstractController.php (Line 165) by:
    protected function tryGetGradedGradeable(Gradeable $gradeable, string $submitter_id, bool $render_json = true) {

Message:
Argument 2 passed to app\controllers\AbstractController::tryGetGradedGradeable() must be of the type string, null given, called in /usr/local/submitty/site/app/controllers/grading/ElectronicGraderController.php on line 1557

Stack Trace:
#0 /usr/local/submitty/site/app/controllers/grading/ElectronicGraderController.php(1557): app\controllers\AbstractController->tryGetGradedGradeable()
#1 unknown file(unknown line): app\controllers\grading\ElectronicGraderController->showGrading()
#2 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(254): call_user_func_array()
#3 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(232): app\libraries\routers\WebRouter->run()
#4 /usr/local/submitty/site/public/index.php(131): app\libraries\routers\WebRouter::getWebResponse()

URL: https://submitty.cs.rpi.edu//courses/f22/csci1200/gradeable/test02/grading/grade?sort=id&direction=ASC&from=cutler&to=next&filter=default&navigate_assigned_students_only=false
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

**Comment by bmcutler** [comment]
I see my username in the URL, is that part of the bug?  Shouldn't it be anon id?
